# Database Config
DB_URL = "https://vyomavswxryemnyufixw.supabase.co"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5b21hdnN3eHJ5ZW1ueXVmaXh3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTAwNDEyMCwiZXhwIjoyMDU2NTgwMTIwfQ.77CNBmiHa7Iz6TYIChgpwzaSUDyiLPOefPONcmrtOR8"
